version: "3.9"
services:
  db-fltracker:
    image: postgres:10.3
    restart: always
    environment:
      POSTGRES_DB: "fltracker"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
    ports:
      - "5435:5432"
  db-fltracker-auth:
    image: postgres:10.3
    restart: always
    environment:
      POSTGRES_DB: "fltracker-auth"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
    ports:
      - "5436:5432"