version: "3.9"
services:
  db-fltracker:
    image: postgres:10.3
    restart: always
    environment:
      POSTGRES_DB: "fltracker"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
    ports:
      - "5435:5432"