spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:postgresql://localhost:5435/fltracker?stringtype=unspecified
    username: user
    password: password

screenshots:
  path: ${user.dir}${file.separator}screens${file.separator}